--- #YAML:1.0
name: CGI-Application
version: 4.0_2
author:
  - Jesse Erlbaum <jesse@erlbaum.net>
abstract: Framework for building reusable web-applications
license: perl
requires:
  CGI: 0
  Carp: 0
  HTML::Template: 0
  Test::More: 0
provides:
  CGI::Application:
    file: lib/CGI/Application.pm
    version: 4.0_2
  CGI::Application::Mailform:
    file: lib/CGI/Application/Mailform.pm
generated_by: Module::Build version 0.2606
