--- #YAML:1.0
name: CGI-Application
version: 3.30
license: perl
distribution_type: module
requires:
  CGI: 0
  Carp: 0
  HTML::Template: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  CGI::Application:
    file: lib/CGI/Application.pm
    version: 3.30
  CGI::Application::Mailform:
    file: lib/CGI/Application/Mailform.pm
generated_by: Module::Build version 0.21
