--- #YAML:1.0
name: CGI-Application
version: 3.22
author:
  - Jesse Erlbaum <jesse@erlbaum.net>
abstract: Framework for building reusable web-applications
license: perl
generated_by: Module::Build version 0.22, without YAML.pm
