---
name: CGI-Application
version: 4.30
author:
  - 'Jesse Erlbaum <jesse@erlbaum.net>'
  - 'Mark Stosberg <mark@summersault.com>'
  - "with the help of many others!"
abstract: Framework for building reusable web-applications
license: perl
requires:
  CGI: 0
  Carp: 0
  Class::ISA: 0
  HTML::Template: 0
  Test::More: 0.47
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  file:
provides:
  CGI::Application:
    file: lib/CGI/Application.pm
    version: 4.30
  CGI::Application::Mailform:
    file: lib/CGI/Application/Mailform.pm
resources:
  license: ~
